MS={'BDI': [{
        '1': 'Sadness.',
        '2': 'Pessimism.',
        '3': 'Past Failure.',
        '4': 'Loss of Pleasure.',
        '5': 'Guilty Feelings.',
        '6': 'Punishment Feelings.',
        '7': 'Self-Dislike.',
        '8': 'Self-Accusations.',
        '9': 'Suicidal Thoughts or Wishes.',
        '10': 'Crying.',
        '11': 'Agitation.',
        '12': 'Loss of Interest.',
        '13': 'Indecisiveness.',
        '14': 'Worthlessness.',
        '15': 'Loss of Energy.',
        '16': 'Changes in Sleeping Pattern.',
        '17': 'Irritability.',
        '18': 'Changes in Appetite.',
        '19': 'Concentration Difficulty.',
        '20': 'Tiredness or Fatigue.',
        '21': 'Changes in Interest in Sex.'
    },{
                '1': ('I do not feel sad', 'I feel sad much of the time', 'I am sad all the time',
                      'I am so sad or unhappy that I can not stand it'),
                '2': ('I am not discouraged about my future', 'I feel discouraged about my future',
                      'I feel I have nothing to look forward to',
                      'I feel the future is hopeless and that things cannot improve'),
                '3': ('I do not feel like a failure', 'I feel I have failed more than the average person',
                      'As I look back on my life, all I can see is a lot of failures',
                      'I feel I am a complete failure as a person'),
                '4': ('I get as much pleasure as I ever did from the things I enjoy',
                      'I do not enjoy things as much as I used to',
                      'I get very little pleasure from the things I used to enjoy',
                      'I can not get any pleasure from the things I used to enjoy'),
                '5': (
                    'I do not feel guilty', 'I feel guilty a good part of the time',
                    'I feel quite guilty most of the time',
                    'I feel guilty all of the time'),
                '6': ('I do not feel I am being punished', 'I feel I may be punished', 'I expect to be punished',
                      'I feel I am being punished'),
                '7': (
                    'I feel the same about myself as ever', 'I have lost confidence in myself',
                    'I am disappointed in myself',
                    'I dislike myself'),
                '8': (
                    'I do not criticize or blame myself more than usual',
                    'I am more self-critical or blaming than usual',
                    'I criticize myself for all of my faults', 'I blame myself for everything bad that happens'),
                '9': ('I do not have any thoughts of killing myself.',
                      'I have thoughts of killing myself, but I would not carry them out.',
                      'I would like to kill myself.',
                      'I would kill myself if I had the chance.'),
                '10': ('I do not cry any more than usual.', 'I cry more than I used to.', 'I cry all the time now.',
                       'I used to be able to cry, but now I can not cry even though I want to.'),
                '11': ('I am no more restless or wound up than usual.', 'I feel more restless or wound up than usual.',
                       'I am so restless or agitated that it is hard to stay still.',
                       'I am so restless or agitated that I have to keep moving or doing something.'),
                '12': ('I have not lost interest in other people or activities.',
                       'I am less interested in other people or things than before.',
                       'I have lost most of my interest in other people or things.',
                       'It is hard to get interested in anything.'),
                '13': (
                'I make decisions about as well as ever.', 'I find it more difficult to make decisions than usual.',
                'I have greater difficulty in making decisions than I used to.',
                'I can not make decisions at all anymore.'),
                '14': (
                'I do not feel I am worthless.', 'I do not consider myself as worthwhile and useful as I used to.',
                'I feel more worthless as compared to other people.', 'I feel utterly worthless.'),
                '15': ('I have as much energy as ever.', 'I have less energy than I used to have.',
                       'I do not have enough energy to do very much.', 'I do not have enough energy to do anything.'),
                '16': ('I have not experienced any change in my sleeping pattern.', 'I sleep somewhat less than usual.',
                       'I sleep a lot less than usual', 'I wake up 1-2 hours early and can not get back to sleep'),
                '17': ('I am no more irritable than usual.', 'I am more irritable than usual.',
                       'I am much more irritable than usual.', 'I am irritable all the time.'),
                '18': ('I have not experienced any change in my appetite.', 'My appetite is somewhat less than usual.',
                       'My appetite is much less than before.', 'I have no appetite at all'),
                '19': ('I can concentrate as well as ever.', 'I can not concentrate as well as usual.',
                       'It is hard to keep my mind on anything for very long.',
                       'I find I can not concentrate on anything.'),
                '20': (
                    'I am no more tired or fatigued than usual.',
                    'I get more tired or fatigued more easily than usual.',
                    'I am too tired or fatigued to do a lot of the things I used to do.',
                    'I am too tired or fatigued to do most of the things I used to do.'),
                '21': ('I have not noticed any recent change in interest in sex.',
                       'I am less interested in sex than I used to be.', 'I have almost no interest in sex.',
                       'I have lost interest in sex completely.')
            }],
    'INQ-15':[{
        '1': 'These days, the people in my life would be better off if I were gone.',
        '2': 'These days, the people in my life would be happier without me.',
        '3': 'These days, I think I am a burden on society.',
        '4': 'These days, I think my death would be a relief to the people in my life',
        '5': 'These days, I think the people in my life wish they could be rid of me.',
        '6': 'These days, I think I make things worse for the people in my life.',
        '7': 'These days, other people care about me.',
        '8': 'These days, I feel like I belong.',
        '9': 'These days, I rarely interact with people who care about me',
        '10': 'These days, I am fortunate to have many caring and supportive friends.',
        '11': 'These days, I feel disconnected from other people.',
        '12': 'These days, I often feel like an outsider in social gatherings.',
        '13': 'These days, I feel that there are people I can turn to in times of need.',
        '14': 'These days, I am close to other people.',
        '15': 'These days, I have at least one satisfying interaction every day.'
    },{
        '1': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '2': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '3': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '4': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '5': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '6': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '7': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '8': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '9': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '10': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '11': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '12': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '13': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '14': ('Not at all true for me', 'Somewhat true for me', 'Very true for me'),
        '15': ('Not at all true for me', 'Somewhat true for me', 'Very true for me')
    }]}